export interface CountryEntry {
  alpha2: string;
  name: string;
}

export const COUNTRY_LIST: CountryEntry[] = [
  { alpha2: "US", name: "United States" },
  { alpha2: "GB", name: "United Kingdom" },
  { alpha2: "CA", name: "Canada" },
  { alpha2: "AU", name: "Australia" },
  { alpha2: "DE", name: "Germany" },
  { alpha2: "FR", name: "France" },
  { alpha2: "JP", name: "Japan" },
  { alpha2: "KR", name: "South Korea" },
  { alpha2: "SG", name: "Singapore" },
  { alpha2: "BR", name: "Brazil" },
  { alpha2: "MX", name: "Mexico" },
  { alpha2: "IN", name: "India" },
  { alpha2: "IT", name: "Italy" },
  { alpha2: "ES", name: "Spain" },
  { alpha2: "NL", name: "Netherlands" },
  { alpha2: "CH", name: "Switzerland" },
  { alpha2: "SE", name: "Sweden" },
  { alpha2: "NO", name: "Norway" },
  { alpha2: "DK", name: "Denmark" },
  { alpha2: "FI", name: "Finland" },
  { alpha2: "AT", name: "Austria" },
  { alpha2: "BE", name: "Belgium" },
  { alpha2: "PT", name: "Portugal" },
  { alpha2: "IE", name: "Ireland" },
  { alpha2: "PL", name: "Poland" },
  { alpha2: "CZ", name: "Czech Republic" },
  { alpha2: "HU", name: "Hungary" },
  { alpha2: "RO", name: "Romania" },
  { alpha2: "BG", name: "Bulgaria" },
  { alpha2: "HR", name: "Croatia" },
  { alpha2: "GR", name: "Greece" },
  { alpha2: "NZ", name: "New Zealand" },
  { alpha2: "ZA", name: "South Africa" },
  { alpha2: "TR", name: "Turkey" },
  { alpha2: "IL", name: "Israel" },
  { alpha2: "AE", name: "United Arab Emirates" },
  { alpha2: "SA", name: "Saudi Arabia" },
  { alpha2: "TH", name: "Thailand" },
  { alpha2: "PH", name: "Philippines" },
  { alpha2: "MY", name: "Malaysia" },
  { alpha2: "ID", name: "Indonesia" },
  { alpha2: "VN", name: "Vietnam" },
  { alpha2: "TW", name: "Taiwan" },
  { alpha2: "HK", name: "Hong Kong" },
  { alpha2: "CL", name: "Chile" },
  { alpha2: "CO", name: "Colombia" },
  { alpha2: "PE", name: "Peru" },
  { alpha2: "AR", name: "Argentina" },
  { alpha2: "NG", name: "Nigeria" },
  { alpha2: "KE", name: "Kenya" },
  { alpha2: "GH", name: "Ghana" },
  { alpha2: "EG", name: "Egypt" },
  { alpha2: "PK", name: "Pakistan" },
  { alpha2: "BD", name: "Bangladesh" },
  { alpha2: "LK", name: "Sri Lanka" },
  { alpha2: "UA", name: "Ukraine" },
  { alpha2: "SK", name: "Slovakia" },
  { alpha2: "SI", name: "Slovenia" },
  { alpha2: "LT", name: "Lithuania" },
  { alpha2: "LV", name: "Latvia" },
  { alpha2: "EE", name: "Estonia" },
  { alpha2: "CY", name: "Cyprus" },
  { alpha2: "MT", name: "Malta" },
  { alpha2: "LU", name: "Luxembourg" },
  { alpha2: "IS", name: "Iceland" },
];
