import { ChainVM } from "@reservoir0x/relay-sdk";

export const solanaChain = {
  id: 792703809,
  name: "solana",
  displayName: "Solana",
  httpRpcUrl: "https://api.mainnet-beta.solana.com",
  wsRpcUrl: "",
  explorerUrl: "https://solscan.io",
  explorerName: "SolScan",
  depositEnabled: true,
  tokenSupport: "All",
  disabled: false,
  partialDisableLimit: 0,
  blockProductionLagging: false,
  currency: {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    address: "11111111111111111111111111111111",
    decimals: 9,
    supportsBridging: false,
  },
  withdrawalFee: 0,
  depositFee: 0,
  surgeEnabled: false,
  erc20Currencies: [
    {
      id: "pengu",
      symbol: "PENGU",
      name: "Pudgy Penguins",
      address: "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
      decimals: 6,
      supportsBridging: true,
      withdrawalFee: 0,
      depositFee: 0,
      surgeEnabled: false,
    },
    {
      id: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      decimals: 6,
      supportsBridging: true,
      supportsPermit: true,
      withdrawalFee: 5,
      depositFee: 2,
      surgeEnabled: false,
    },
  ],
  iconUrl: "https://assets.relay.link/icons/792703809/light.png",
  contracts: {
    multicall3: "",
    multicaller: "",
    onlyOwnerMulticaller: "",
    relayReceiver: "",
    erc20Router: "",
    approvalProxy: "",
  },
  vmType: "svm" as ChainVM,
  baseChainId: 1,
};
