import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PrivyProvider from "../context/PrivyProvider";
import "../styles/index.scss";
import { fetchCommunityCoins } from "@/actions/fetch-community-coins";
import { fetchSolanaCoins } from "@/actions/fetch-solana-coins";
import { fetchTokensForChain } from "@/actions/fetch-tokens-for-chain";
import TokenModal from "@/components/token-modal";
import { CommunityCoinsProvider } from "@/context/FarcasterCommunityTokensProvider";
import { SolanaCoinsProvider } from "@/context/DexScreenerTrendingSolataTokensProvider";
import { GeckoTokensProvider } from "@/context/GeckoTerminalCoinsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const community = await fetchCommunityCoins();
  // console.log("solana coins", solana);

  // const s = await searchDexTokens({ network: "base", query: "degen" });

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrivyProvider>
          <SolanaCoinsProvider>
            <CommunityCoinsProvider>
              <GeckoTokensProvider>
                <div className="main">
                  {/* <TokenModal
              geckoCoins={gecko}
              communityCoins={community}
              solanaCoins={solana}
            /> */}
                  {children}
                </div>
              </GeckoTokensProvider>
            </CommunityCoinsProvider>
          </SolanaCoinsProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
