import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PrivyProvider from "../context/PrivyProvider";
import "../styles/index.scss";
import { fetchCommunityCoins } from "@/actions/fetch-community-coins";
import { fetchSolanaCoins } from "@/actions/fetch-solana-coins";
import { fetchTokensForChain } from "@/actions/fetch-tokens-for-chain";
import { searchDexTokens } from "@/actions/search-dex-tokens";
import TokenModal from "@/components/token-modal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const community = await fetchCommunityCoins();
  const solana = await fetchSolanaCoins();
  const gecko = await fetchTokensForChain("base");

  // const s = await searchDexTokens({ network: "base", query: "degen" });

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrivyProvider>
          <div className="main">
            <TokenModal
              geckoCoins={gecko}
              communityCoins={community}
              solanaCoins={solana}
            />
            {children}
          </div>
        </PrivyProvider>
      </body>
    </html>
  );
}
