// import type { Metadata } from "next";
import { Fira_Code, Handjet } from "next/font/google";
import PrivyProvider from "../context/PrivyProvider";
import "../styles/index.scss";
import { CommunityCoinsProvider } from "@/context/FarcasterCommunityTokensProvider";
import { SolanaCoinsProvider } from "@/context/DexScreenerTrendingSolataTokensProvider";
import { GeckoTokensProvider } from "@/context/GeckoTerminalCoinsProvider";
import MoonPayContextProvider from "@/context/MoonpayProvider";
import { TokenModalProvider } from "@/context/TokenModalProvider";
import { ActiveWalletProvider } from "@/context/ActiveWalletContext";
import { SlippageProvider } from "@/context/SlippageContext";
import Header from "@/components/header";
import { RelayKitProviderWrapper as RelayKitProvider } from "@/context/RelayKitProvider";

const firaCode = Fira_Code({
  subsets: ["latin"], // adjust as needed
  variable: "--font-fira-code",
});

// load Handjet as a CSS variable
const handjet = Handjet({
  subsets: ["latin"],
  variable: "--font-handjet",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const community = await fetchCommunityCoins();
  // console.log("solana coins", solana);

  // const s = await searchDexTokens({ network: "base", query: "degen" });

  return (
    <html lang="en">
      <body className={`${firaCode.variable} ${handjet.variable}`}>
        <PrivyProvider>
          <SolanaCoinsProvider>
            <CommunityCoinsProvider>
              <GeckoTokensProvider>
                <MoonPayContextProvider>
                  <ActiveWalletProvider>
                    <TokenModalProvider>
                      <RelayKitProvider>
                        <SlippageProvider>
                          <Header />
                          <div className="main">
                                                          {/* <TokenModal
                                            geckoCoins={gecko}
                                            communityCoins={community}
                                            solanaCoins={solana}
                                          /> */}
                            {children}
                          </div>
                        </SlippageProvider>
                      </RelayKitProvider>
                    </TokenModalProvider>
                  </ActiveWalletProvider>
                </MoonPayContextProvider>
              </GeckoTokensProvider>
            </CommunityCoinsProvider>
          </SolanaCoinsProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
